### PR TITLE
Added RAP guidelines

### PR DESCRIPTION
**Pull request by melissaxd96**
- added RAP.md
- added node module package: generate table of content for markdown 
- added js file to create table of contents

### CODE REVIEW

**Review by jcailan — APPROVED** [review]
🫡

**Review by jcailan — CHANGES_REQUESTED** [review]
You can set VSCode to always use commit signing when using the Git panel to do the commits:
image

**Review by melissaxd96 — COMMENTED** [review]
I have updated in the settings :)

**Review by jcailan — APPROVED** [review]

**Comment by jcailan** [comment]
> I have updated in the settings :)

@melissaxd96 Still didn't work... check your commits

**Pull request closed without merging**
